### ISSUE TITLE
Unable to run BurnBytes

### ISSUE THREAD

**Issue by MD55DM** [mirinsoft/burnbytes#1]
Hello, I'm unable to successfully run BurnBytes (any version, from first release to latest available).

I can start the program, than, after selecting the drive to clean, the program start and quit after one second or less.

Crash report:

Description:
Faulting application name: Burnbytes.exe, version: 0.11.1.0, time stamp: 0x8414c48e
Faulting module name: KERNELBASE.dll, version: 10.0.19041.207, time stamp: 0x746c1866
Exception code: 0xe0434352
Fault offset: 0x0000000000023e49
Faulting process ID: 0x23c4
Faulting application start time: 0x01d63499e28b85c5
Faulting application path: D:\------\Portable Apps\Mirinsoft\Burnbytes\Burnbytes.exe
Faulting module path: C:\Windows\System32\KERNELBASE.dll

OS Information:
Windows 10 Pro
Version 2004
OS build 19041.264

**Comment by Belim** [comment]
Could be related to your .Net framework version. 
Burnbytes is built with 4.7.2. As minimum requirement 4.5 should be installed

Another option is to check the Application log accessible via the Windows Event Viewer.
You can see these events here:
Event Viewer (Local) > Windows Logs > Application

**Comment by MD55DM** [comment]
Thanks for your help attempt, really appreciated!
---
My event viewer report:
Application: Burnbytes.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.ArgumentNullException
   at System.Guid..ctor(System.String)
   at Comet.Api.InitializeHandler(System.String, System.String)
   at Comet.UI.Scanner.<.ctor>b__1_0()
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)
   at System.Threading.ThreadHelper.ThreadStart()
---

**Comment by fadinzr** [comment]
same exact issue.

> Hello, I'm unable to successfully run BurnBytes (any version, from first release to latest available).
> 
> I can start the program, than, after selecting the drive to clean, the program start and quit after one second or less.
> 
> Crash report:
> 
> Description:
> Faulting application name: Burnbytes.exe, version: 0.11.1.0, time stamp: 0x8414c48e
> Faulting module name: KERNELBASE.dll, version: 10.0.19041.207, time stamp: 0x746c1866
> Exception code: 0xe0434352
> Fault offset: 0x0000000000023e49
> Faulting process ID: 0x23c4
> Faulting application start time: 0x01d63499e28b85c5
> Faulting application path: D:------\Portable Apps\Mirinsoft\Burnbytes\Burnbytes.exe
> Faulting module path: C:\Windows\System32\KERNELBASE.dll
> 
> OS Information:
> Windows 10 Pro
> Version 2004
> OS build 19041.264

same exact issue tried to install the mentioned .Net Framework and it says the updates are already installed.

**Comment by MD55DM** [comment]
BurnBytes is the only app from Mirinsoft that I cannot run. 
Cleanmgr+, Debotnet and SharpApp are working fine since first alpha/beta/stable release.

**Comment by Zazulas** [comment]
I'm not opening a new issue because I also have the same problem with being unable to run Burnbytes to its conclusion (it does start, but crashes while running, with no error message).

**Event report:**
Faulting application name: Burnbytes.exe, version: 0.12.2.0, time stamp: 0x855fcc9a
Faulting module name: KERNELBASE.dll, version: 10.0.17763.1518, time stamp: 0xff301d3c
Exception code: 0xe0434352
Fault offset: 0x00000000000396c9
Faulting process id: 0x17bc
Faulting application start time: 0x01d6a83d6689d592
Faulting application path: D:\---------\Downloads\Windows\burnbytes\Burnbytes.exe
Faulting module path: C:\Windows\System32\KERNELBASE.dll
Report Id: 4f626000-aa3c-4e84-a427-3933803ba68a
Faulting package full name: 
Faulting package-relative application ID: 

**OS/.NET info:**
Windows 10 Enterprise 64-bit
Version 1809
Build 17763.1554
Framework version 4.7.03190
